spring:
  application:
    name: fintracker
  datasource:
    url: jdbc:postgresql://fintracker-db:5432/fin-tracker-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /api/v1

